<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Fixtures\aura-asuna.jpg" />
    <PackageReference Include="Avalonia.Headless" Version="11.3.20" />
    <PackageReference Include="Avalonia.Skia" Version="11.3.20" />
    <ProjectReference Include="../../Eve-O-Preview.UI/Eve-O-Preview.UI.csproj" />
  </ItemGroup>
</Project>
